// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id":"",
    "aws_user_pools_id":"eu-west-1_d7fdSAgua",
    "aws_user_pools_web_client_id":"7tnqml77fnoe0rde2nu2ar58nv",
};

export default awsmobile;